In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("spam.csv", encoding="latin1")

In [4]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
df.shape

(5572, 5)

In [7]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

In [8]:
df = df [["v1", "v2"]]

In [9]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.rename(columns={"v1": "label", "v2": "message" },inplace=True)

In [11]:
df.head(2)

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...

In [12]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(403)

In [14]:
df = df.drop_duplicates()

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
print(f"Spam Message : {(df["label"] == "spam").sum()}")

Spam Message : 653

In [17]:
print(f"HAM Message : {(df["label"] == "ham").sum()}")

HAM Message : 4516

In [18]:
print("FREE ENTry of concert ".lower())

free entry of concert

In [19]:
df["message"] = df["message"].str.lower()

In [20]:
df.head()

  label                                            message
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [21]:
import re

In [22]:
example = "Free enetry in 2 a weklk !!!! hurrah you won fa tesxt 737377373"

In [23]:
example_clean = re.sub(r"[^a-z \s]", "" , example)

In [24]:
print(example_clean)

ree enetry in  a weklk  hurrah you won fa tesxt

In [25]:
df['message'] = df['message'].apply( lambda x: re.sub(r'[^a-z\s]','',x))

In [26]:
df.head()

  label                                            message
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in  a wkly comp to win fa cup final...
3   ham        u dun say so early hor u c already then say
4   ham  nah i dont think he goes to usf he lives aroun...

In [27]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (4.68.3)
Requirement already satisfied: colorama in c:\users\user'\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from click->nltk) (0.4.6)

In [28]:
import nltk

In [ ]:
nltk.download("punkt")

In [ ]:
nltk.download("stopwords")

In [31]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user'\AppData\Roaming\nltk_data...

True

In [32]:
from nltk.tokenize import word_tokenize

In [33]:
sample = "hellp alll how are you doing today "

In [34]:
sample_token = word_tokenize(sample)

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - "C:\\Users\\user'/nltk_data"
    - 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.3824.0_x64__qbz5n2kfra8p0\\nltk_data'
    - 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.3824.0_x64__qbz5n2kfra8p0\\share\\nltk_data'
    - 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.3824.0_x64__qbz5n2kfra8p0\\lib\\nltk_data'
    - "C:\\Users\\user'\\AppData\\Roaming\\nltk_data"
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [ ]:
print(sample_token)

In [ ]:
from nltk.corpus import stopwords

In [ ]:
df['message'] = df['message'].apply( lambda x : " ".join (
    [words for words in word_tokenize(x) 
     if words not in stopwords]
))

In [ ]:
print (df["message"][10])

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
df["message"] = df["message"].apply(
    lambda x : " ".join ([stemmer.stem(word) for word in x.split() ]) 
)

In [ ]:
from sklearn.feature_extraction.text import  TfidfVectorizer

In [ ]:
X = df["message"]

In [ ]:
Y = df["label"]

In [ ]:
tfidf = TfidfVectorizer(max_features=3000)

In [ ]:
X_vec = tfidf.fit_transform(X)

In [ ]:
X_vec.shape[1]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train, Y_train)

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix ,classification_report

In [ ]:
accuracy_score = accuracy_score(Y_test, Y_pred)

In [ ]:
print(accuracy_score)

In [ ]:
cm = confusion_matrix(Y_test,Y_pred)

In [ ]:
cm

In [ ]:
def precit_message (message ):
    msg = message.lower()
    msg = re.sub((r'[^a-z\s]'), "",msg)
    token = word_tokenize(msg)
    token= [w for w in token 
           if w not in stopwords]
    tokens= [stemmer.stem(w) for w in token]
    clean_msg = " ".join(tokens)
    vec = tfidf.transform([clean_msg])
    result = model.predict(vec)[0]
    prob = model.predict(vec)[0]
    return result, prob

In [ ]:
text_msg = """Congratulation you won a lotterly of 100000 rs click on thhe clink to claim your winning price .
    other wise it will be given to others . 

    URgent click the link to claim your Money 
    """

In [ ]:
precit_message(text_msg)